### ISSUE TITLE
RUNTIME: FATAL EXCEPTION: Computer Player | java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Kai-Richardson** [RJMNillo/CS301ASSN5GoTest#12]
Stack Trace:
```
E/AndroidRuntime: FATAL EXCEPTION: Computer Player
    Process: com.example.cs301assn5go, PID: 26020
    java.lang.ArrayIndexOutOfBoundsException: length=13; index=13
        at com.example.cs301assn5go.Go.GoLocalGame.checkIfCaptured(GoLocalGame.java:334)
        at com.example.cs301assn5go.Go.GoLocalGame.makeMove(GoLocalGame.java:187)
        at com.example.cs301assn5go.game.GameFramework.GameFramework.LocalGame.checkAndHandleAction(LocalGame.java:302)
        at com.example.cs301assn5go.game.GameFramework.GameFramework.LocalGame.receiveMessage(LocalGame.java:259)
        at com.example.cs301assn5go.game.GameFramework.GameFramework.LocalGame.access$100(LocalGame.java:35)
        at com.example.cs301assn5go.game.GameFramework.GameFramework.LocalGame$MyHandler.handleMessage(LocalGame.java:434)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at com.example.cs301assn5go.game.GameFramework.GameFramework.LocalGame.sendAction(LocalGame.java:399)
        at com.example.cs301assn5go.Go.GoDumbAI.receiveInfo(GoDumbAI.java:59)
        at com.example.cs301assn5go.game.GameFramework.GameFramework.GameComputerPlayer$MyRunnable.run(GameComputerPlayer.java:246)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:208)
        at com.example.cs301assn5go.game.GameFramework.GameFramework.GameComputerPlayer$1.run(GameComputerPlayer.java:145)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by hendersj22** [comment]
How did you cause this?
