### ISSUE TITLE
[RUNTIME] GameFramework.infoMessage.IllegalMoveInfo cannot be cast to GoState

### ISSUE THREAD

**Issue by Kai-Richardson** [RJMNillo/CS301ASSN5GoTest#2]
It looks like receiveInfo is getting passed an IllegalMoveInfo, which is then being casted to a GoState here: https://github.com/RJMNillo/CS301ASSN5GoTest/blob/a452190150ac5d56edddbb146cb750fce313ef5b/app/src/main/java/com/example/cs301assn5go/Go/GoDumbAI.java#L22

I would check for being passed an illegalmove above and either output an error or return.

Call Stack:
```
2010-01-21 20:37:24.154 21368-21423/com.example.cs301assn5go E/AndroidRuntime: FATAL EXCEPTION: Computer Player
    Process: com.example.cs301assn5go, PID: 21368
    java.lang.ClassCastException: com.example.cs301assn5go.game.GameFramework.GameFramework.infoMessage.IllegalMoveInfo cannot be cast to com.example.cs301assn5go.Go.GoState
        at com.example.cs301assn5go.Go.GoDumbAI.receiveInfo(GoDumbAI.java:22)
        at com.example.cs301assn5go.game.GameFramework.GameFramework.GameComputerPlayer$MyRunnable.run(GameComputerPlayer.java:246)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:208)
        at com.example.cs301assn5go.game.GameFramework.GameFramework.GameComputerPlayer$1.run(GameComputerPlayer.java:145)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by MwKau** [comment]
Nice catch! Fixed

**Comment by Kai-Richardson** [comment]
Fixed.
